#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

THEMES=(
  "Gruber Darker"
  "Catppuccin Mocha"
  "Dracula"
  "Ayu Mirage"
  "Everforest Dark Hard"
  "Flexoki Dark"
  "GitHub Dark"
  "Gruvbox Dark"
  "Nightfox"
  "Nord"
  "One Half Dark"
  "TokyoNight Storm"
  "Monokai Pro"
  "Sonokai"
  "Catppuccin Macchiato"
  "Material"
)
CSS_TARGET="${SCRIPT_DIR}/codex-theme.css"
SRC_DIR="${GHOSTTY_THEME_DIR:-/Applications/Ghostty.app/Contents/Resources/ghostty/themes}"

usage() {
  cat <<USAGE
Usage:
  codex-theme-switcher.sh [theme name]
  codex-theme-switcher.sh --menu

Examples:
  codex-theme-switcher.sh "Dracula"
  codex-theme-switcher.sh --menu
USAGE
}

hex_to_rgb() {
  local hex="${1#\#}"
  if [ "${#hex}" -eq 3 ]; then
    hex="${hex:0:1}${hex:0:1}${hex:1:1}${hex:1:1}${hex:2:1}${hex:2:1}"
  fi
  local r=$((16#${hex:0:2}))
  local g=$((16#${hex:2:2}))
  local b=$((16#${hex:4:2}))
  echo "$r $g $b"
}

mix_hex() {
  local a="$1" b="$2" ratio="$3"
  read -r ar ag ab <<<"$(hex_to_rgb "$a")"
  read -r br bg bb <<<"$(hex_to_rgb "$b")"
  awk -v ar="$ar" -v ag="$ag" -v ab="$ab" -v br="$br" -v bg="$bg" -v bb="$bb" -v ratio="$ratio" 'BEGIN {
    mr = int(ar*(1-ratio)+br*ratio + 0.5)
    mg = int(ag*(1-ratio)+bg*ratio + 0.5)
    mb = int(ab*(1-ratio)+bb*ratio + 0.5)
    printf("#%02x%02x%02x\n", mr, mg, mb)
  }'
}

choose_menu() {
  local theme_choices=""
  local theme escaped
  for theme in "${THEMES[@]}"; do
    escaped="${theme//\"/\\\"}"
    if [ -n "$theme_choices" ]; then
      theme_choices+=", "
    fi
    theme_choices+="\"$escaped\""
  done

  osascript <<OSA
set themeChoices to {$theme_choices}
set picked to choose from list themeChoices with title "Codex Theme Switcher" with prompt "Pick a Ghostty-based preset"
if picked is false then
  return ""
else
  return item 1 of picked
end if
OSA
}

get_field() {
  local file="$1" key="$2"
  awk -F'=' -v key="$key" '$1 ~ "^"key" *$" {gsub(/ /, "", $2); print $2; exit}' "$file"
}

get_palette() {
  local file="$1" idx="$2"
  sed -n "s/^palette *= *${idx}=\\(#[0-9a-fA-F]\\+\\).*/\\1/p" "$file" | head -n 1
}

THEME="${1:-}"
if [ "${THEME:-}" = "--help" ] || [ "${THEME:-}" = "-h" ]; then
  usage
  exit 0
fi

if [ "${THEME:-}" = "--menu" ] || [ -z "${THEME:-}" ]; then
  THEME="$(choose_menu | tr -d '\r')"
fi

if [ -z "${THEME:-}" ]; then
  echo "No theme selected."
  exit 0
fi

if [ ! -d "$SRC_DIR" ]; then
  echo "Ghostty themes directory not found: $SRC_DIR" >&2
  echo "Install Ghostty or set GHOSTTY_THEME_DIR to your Ghostty themes path." >&2
  exit 1
fi

FILE="$SRC_DIR/$THEME"
if [ ! -f "$FILE" ]; then
  echo "Theme not found: $THEME" >&2
  exit 1
fi

bg="$(get_field "$FILE" "background")"
fg="$(get_field "$FILE" "foreground")"
cursor="$(get_field "$FILE" "cursor-color")"
sel_bg="$(get_field "$FILE" "selection-background")"
sel_fg="$(get_field "$FILE" "selection-foreground")"
p0="$(get_palette "$FILE" 0)"
p1="$(get_palette "$FILE" 1)"
p2="$(get_palette "$FILE" 2)"
p3="$(get_palette "$FILE" 3)"
p4="$(get_palette "$FILE" 4)"
p5="$(get_palette "$FILE" 5)"
p6="$(get_palette "$FILE" 6)"
p7="$(get_palette "$FILE" 7)"
p8="$(get_palette "$FILE" 8)"
p9="$(get_palette "$FILE" 9)"
p10="$(get_palette "$FILE" 10)"
p11="$(get_palette "$FILE" 11)"
p12="$(get_palette "$FILE" 12)"
p13="$(get_palette "$FILE" 13)"
p14="$(get_palette "$FILE" 14)"
p15="$(get_palette "$FILE" 15)"

bg2="$(mix_hex "$bg" "${p8:-$fg}" 0.30)"
bg3="$(mix_hex "$bg" "$fg" 0.12)"
text2="$(mix_hex "$fg" "$bg" 0.28)"
text3="$(mix_hex "$fg" "$bg" 0.45)"
muted_text="$(mix_hex "$fg" "$bg" 0.38)"
disabled_text="$(mix_hex "$fg" "$bg" 0.56)"
placeholder_text="$(mix_hex "$fg" "$bg" 0.34)"
icon_text="$(mix_hex "$fg" "$bg" 0.22)"
line_number_text="$(mix_hex "$fg" "$bg" 0.50)"
border="$(mix_hex "$sel_bg" "$bg" 0.50)"
muted_border="$(mix_hex "$border" "$bg" 0.40)"
panel_bg="$(mix_hex "$bg" "$bg2" 0.35)"
elevated_bg="$(mix_hex "$bg2" "$fg" 0.08)"
input_bg="$(mix_hex "$bg" "$bg2" 0.52)"
hover_bg="$(mix_hex "$bg2" "$fg" 0.14)"
active_bg="$(mix_hex "$bg2" "${p4:-$cursor}" 0.22)"
tab_active="$(mix_hex "$bg2" "$fg" 0.05)"
tab_inactive="$(mix_hex "$bg" "$bg2" 0.44)"
terminal_bg="$(mix_hex "$bg" "#000000" 0.18)"
accent="${p4:-$cursor}"
ansi_black="$(mix_hex "${p0:-$bg}" "$fg" 0.34)"
ansi_bright_black="${p8:-$text3}"
diff_add_fg="$(mix_hex "${p2:-$accent}" "$fg" 0.45)"
diff_remove_fg="$(mix_hex "${p1:-$accent}" "$fg" 0.45)"
diff_add_bg="$(mix_hex "${p2:-$bg2}" "$bg" 0.84)"
diff_remove_bg="$(mix_hex "${p1:-$bg2}" "$bg" 0.84)"
diff_neutral_fg="$text2"
grad1="$(mix_hex "${p4:-$cursor}" "$bg" 0.80)"
grad2="$(mix_hex "${p5:-$cursor}" "$bg" 0.78)"

cat > "$CSS_TARGET" <<CSS
/* Generated by codex-theme-switcher.sh from Ghostty theme: $THEME */
:root {
  --token-bg-primary: $bg !important;
  --token-bg-secondary: $bg2 !important;
  --token-bg-tertiary: $bg3 !important;
  --token-text-primary: $fg !important;
  --token-text-secondary: $text2 !important;
  --token-text-tertiary: $text3 !important;
  --token-border: $border !important;
  --token-focus: $cursor !important;

  --color-token-bg-primary: $bg !important;
  --color-token-bg-secondary: $bg2 !important;
  --color-token-bg-tertiary: $bg3 !important;
  --color-token-main-surface-primary: $bg !important;
  --color-token-main-surface-secondary: $panel_bg !important;
  --color-token-main-surface-tertiary: $elevated_bg !important;
  --color-token-side-bar-background: $panel_bg !important;
  --color-token-input-background: $input_bg !important;
  --color-token-input-foreground: $fg !important;
  --color-token-input-border: $muted_border !important;
  --color-token-terminal-background: $terminal_bg !important;
  --color-token-border-subtle: $muted_border !important;
  --color-token-border-strong: $border !important;
  --color-token-foreground-primary: $fg !important;
  --color-token-foreground-secondary: $text2 !important;
  --color-token-foreground-tertiary: $text3 !important;
  --color-token-foreground-muted: $muted_text !important;
  --color-token-foreground-disabled: $disabled_text !important;
  --color-token-accent: $accent !important;

  --vscode-foreground: $fg !important;
  --vscode-descriptionForeground: $text2 !important;
  --vscode-disabledForeground: $disabled_text !important;
  --vscode-icon-foreground: $icon_text !important;
  --vscode-focusBorder: $cursor !important;
  --vscode-widget-border: $muted_border !important;
  --vscode-widget-shadow: rgba(0,0,0,.45) !important;

  --vscode-editor-background: $bg !important;
  --vscode-editor-foreground: $fg !important;
  --vscode-editorLineNumber-foreground: $line_number_text !important;
  --vscode-editorLineNumber-activeForeground: $text2 !important;
  --vscode-editorWhitespace-foreground: $line_number_text !important;
  --vscode-minimap-foregroundOpacity: $line_number_text !important;
  --vscode-editorCursor-foreground: $cursor !important;
  --vscode-editorWidget-background: $panel_bg !important;
  --vscode-editorWidget-border: $muted_border !important;

  --vscode-sideBar-background: $panel_bg !important;
  --vscode-sideBar-foreground: $fg !important;
  --vscode-sideBarSectionHeader-background: $elevated_bg !important;
  --vscode-sideBarSectionHeader-foreground: $text2 !important;
  --vscode-activityBar-background: $panel_bg !important;
  --vscode-activityBar-foreground: $fg !important;

  --vscode-panel-background: $bg !important;
  --vscode-panel-border: $muted_border !important;
  --vscode-terminal-background: $terminal_bg !important;
  --vscode-terminal-foreground: $fg !important;
  --vscode-terminal-ansiBlack: $ansi_black !important;
  --vscode-terminal-ansiRed: ${p1:-$accent} !important;
  --vscode-terminal-ansiGreen: ${p2:-$accent} !important;
  --vscode-terminal-ansiYellow: ${p3:-$accent} !important;
  --vscode-terminal-ansiBlue: ${p4:-$accent} !important;
  --vscode-terminal-ansiMagenta: ${p5:-$accent} !important;
  --vscode-terminal-ansiCyan: ${p6:-$accent} !important;
  --vscode-terminal-ansiWhite: ${p7:-$fg} !important;
  --vscode-terminal-ansiBrightBlack: $ansi_bright_black !important;
  --vscode-terminal-ansiBrightRed: ${p9:-$accent} !important;
  --vscode-terminal-ansiBrightGreen: ${p10:-$accent} !important;
  --vscode-terminal-ansiBrightYellow: ${p11:-$accent} !important;
  --vscode-terminal-ansiBrightBlue: ${p12:-$accent} !important;
  --vscode-terminal-ansiBrightMagenta: ${p13:-$accent} !important;
  --vscode-terminal-ansiBrightCyan: ${p14:-$accent} !important;
  --vscode-terminal-ansiBrightWhite: ${p15:-$fg} !important;

  --vscode-input-background: $input_bg !important;
  --vscode-input-foreground: $fg !important;
  --vscode-input-border: $muted_border !important;
  --vscode-input-placeholderForeground: $placeholder_text !important;
  --vscode-dropdown-background: $input_bg !important;
  --vscode-dropdown-foreground: $fg !important;
  --vscode-dropdown-border: $muted_border !important;

  --vscode-tab-activeBackground: $tab_active !important;
  --vscode-tab-activeForeground: $fg !important;
  --vscode-tab-inactiveBackground: $tab_inactive !important;
  --vscode-tab-inactiveForeground: $text2 !important;
  --vscode-tab-border: $muted_border !important;

  --vscode-list-hoverBackground: $hover_bg !important;
  --vscode-list-activeSelectionBackground: $active_bg !important;
  --vscode-list-activeSelectionForeground: $fg !important;
  --vscode-list-inactiveSelectionBackground: $hover_bg !important;

  --vscode-statusBar-background: $panel_bg !important;
  --vscode-statusBar-foreground: $fg !important;
  --vscode-textLink-foreground: $accent !important;
  --vscode-textPreformat-foreground: $fg !important;

  --vscode-diffEditor-insertedTextForeground: $diff_add_fg !important;
  --vscode-diffEditor-insertedTextBackground: $diff_add_bg !important;
  --vscode-diffEditor-insertedLineBackground: $diff_add_bg !important;
  --vscode-diffEditor-removedTextForeground: $diff_remove_fg !important;
  --vscode-diffEditor-removedTextBackground: $diff_remove_bg !important;
  --vscode-diffEditor-removedLineBackground: $diff_remove_bg !important;
  --vscode-diffEditor-unchangedRegionForeground: $diff_neutral_fg !important;
  --vscode-diffEditor-unchangedRegionBackground: $panel_bg !important;
}

[data-codex-window-type="electron"] {
  background: radial-gradient(1200px 600px at 10% -20%, $grad1 0%, transparent 55%),
              radial-gradient(1000px 500px at 95% 0%, $grad2 0%, transparent 50%),
              $bg !important;
}

[data-codex-window-type="electron"],
[data-codex-window-type="electron"] body,
[data-codex-window-type="electron"] .main-surface {
  background-color: var(--color-token-main-surface-primary) !important;
  color: var(--color-token-foreground-primary) !important;
}

[data-codex-window-type="electron"] .bg-token-input-background,
[data-codex-window-type="electron"] input,
[data-codex-window-type="electron"] textarea,
[data-codex-window-type="electron"] select {
  background-color: var(--color-token-input-background) !important;
  color: var(--color-token-input-foreground) !important;
  border-color: var(--color-token-input-border) !important;
}

[data-codex-window-type="electron"] input::placeholder,
[data-codex-window-type="electron"] textarea::placeholder {
  color: var(--vscode-input-placeholderForeground) !important;
  opacity: 0.96 !important;
}

[data-codex-window-type="electron"] button svg,
[data-codex-window-type="electron"] [role="button"] svg,
[data-codex-window-type="electron"] [aria-haspopup] svg {
  color: var(--vscode-icon-foreground) !important;
  fill: currentColor !important;
  stroke: currentColor !important;
}

[data-codex-window-type="electron"] [class*="text-token-foreground-tertiary"],
[data-codex-window-type="electron"] [class*="text-token-text-tertiary"] {
  color: var(--color-token-foreground-tertiary) !important;
  opacity: 0.95 !important;
}

[data-codex-window-type="electron"] [class*="text-token-foreground-secondary"],
[data-codex-window-type="electron"] [class*="text-token-text-secondary"] {
  color: var(--color-token-foreground-secondary) !important;
}

[data-codex-window-type="electron"] .bg-token-terminal-background {
  background-color: var(--color-token-terminal-background) !important;
  color: var(--vscode-terminal-foreground) !important;
}

[data-codex-window-type="electron"] .xterm span[style*="color: rgb(0, 0, 0)"],
[data-codex-window-type="electron"] .xterm span[style*="color: rgba(0, 0, 0"] {
  color: var(--vscode-terminal-ansiBlack) !important;
}

[data-codex-window-type="electron"] pre,
[data-codex-window-type="electron"] code,
[data-codex-window-type="electron"] [class*="line-number"],
[data-codex-window-type="electron"] [class*="lineNumber"] {
  color: var(--vscode-editor-foreground) !important;
}

[data-codex-window-type="electron"] pre span[style*="color"],
[data-codex-window-type="electron"] code span[style*="color"] {
  color: color-mix(in oklab, var(--vscode-editor-foreground) 70%, currentColor 30%) !important;
}

[data-codex-window-type="electron"] [class*="diff"] pre,
[data-codex-window-type="electron"] [class*="diff"] code,
[data-codex-window-type="electron"] [class*="viewer"] pre,
[data-codex-window-type="electron"] [class*="viewer"] code {
  color: var(--vscode-textPreformat-foreground) !important;
}

[data-codex-window-type="electron"] [class*="diff"],
[data-codex-window-type="electron"] [data-testid*="diff"],
[data-codex-window-type="electron"] [class*="file-view"],
[data-codex-window-type="electron"] [class*="viewer"] {
  color: var(--vscode-editor-foreground) !important;
}

[data-codex-window-type="electron"] diffs-container,
[data-codex-window-type="electron"] [class*="file-diff"] {
  --diffs-fg: var(--vscode-editor-foreground) !important;
  --diffs-fg-number: var(--vscode-editorLineNumber-foreground) !important;
  --diffs-light: var(--vscode-editor-foreground) !important;
  --diffs-dark-bg: var(--color-token-main-surface-primary) !important;
  --color-text-foreground: var(--vscode-editor-foreground) !important;
  --color-text-foreground-secondary: var(--color-token-foreground-secondary) !important;
  --color-text-foreground-tertiary: var(--color-token-foreground-tertiary) !important;
  --gray-1000: var(--vscode-editor-foreground) !important;
  color: var(--vscode-editor-foreground) !important;
}

[data-codex-window-type="electron"] [class*="diff"] [class*="font-mono"],
[data-codex-window-type="electron"] [data-testid*="diff"] [class*="font-mono"],
[data-codex-window-type="electron"] [class*="file-view"] [class*="font-mono"],
[data-codex-window-type="electron"] [class*="viewer"] [class*="font-mono"] {
  color: color-mix(in oklab, var(--vscode-editor-foreground) 84%, currentColor 16%) !important;
}

[data-codex-window-type="electron"] [class*="font-mono"] {
  color: color-mix(in oklab, var(--vscode-editor-foreground) 88%, currentColor 12%) !important;
}

[data-codex-window-type="electron"] [class*="font-mono"] span,
[data-codex-window-type="electron"] [class*="font-mono"] div {
  color: color-mix(in oklab, var(--vscode-editor-foreground) 86%, currentColor 14%) !important;
}

[data-codex-window-type="electron"] [class*="diff"] [style*="color:#000"],
[data-codex-window-type="electron"] [class*="diff"] [style*="color: #000"],
[data-codex-window-type="electron"] [class*="diff"] [style*="color:#111"],
[data-codex-window-type="electron"] [class*="diff"] [style*="color: #111"],
[data-codex-window-type="electron"] [class*="diff"] [style*="color:#24292e"],
[data-codex-window-type="electron"] [class*="diff"] [style*="color: #24292e"],
[data-codex-window-type="electron"] [class*="diff"] [style*="color: rgb(0, 0, 0)"],
[data-codex-window-type="electron"] [class*="diff"] [style*="color: rgba(0, 0, 0"],
[data-codex-window-type="electron"] [data-testid*="diff"] [style*="color:#000"],
[data-codex-window-type="electron"] [data-testid*="diff"] [style*="color: #000"],
[data-codex-window-type="electron"] [data-testid*="diff"] [style*="color:#111"],
[data-codex-window-type="electron"] [data-testid*="diff"] [style*="color: #111"],
[data-codex-window-type="electron"] [data-testid*="diff"] [style*="color:#24292e"],
[data-codex-window-type="electron"] [data-testid*="diff"] [style*="color: #24292e"],
[data-codex-window-type="electron"] [data-testid*="diff"] [style*="color: rgb(0, 0, 0)"],
[data-codex-window-type="electron"] [data-testid*="diff"] [style*="color: rgba(0, 0, 0"],
[data-codex-window-type="electron"] [class*="file-view"] [style*="color:#000"],
[data-codex-window-type="electron"] [class*="file-view"] [style*="color: #000"],
[data-codex-window-type="electron"] [class*="file-view"] [style*="color:#111"],
[data-codex-window-type="electron"] [class*="file-view"] [style*="color: #111"],
[data-codex-window-type="electron"] [class*="file-view"] [style*="color:#24292e"],
[data-codex-window-type="electron"] [class*="file-view"] [style*="color: #24292e"],
[data-codex-window-type="electron"] [class*="file-view"] [style*="color: rgb(0, 0, 0)"],
[data-codex-window-type="electron"] [class*="file-view"] [style*="color: rgba(0, 0, 0"],
[data-codex-window-type="electron"] [class*="viewer"] [style*="color:#000"],
[data-codex-window-type="electron"] [class*="viewer"] [style*="color: #000"],
[data-codex-window-type="electron"] [class*="viewer"] [style*="color:#111"],
[data-codex-window-type="electron"] [class*="viewer"] [style*="color: #111"],
[data-codex-window-type="electron"] [class*="viewer"] [style*="color:#24292e"],
[data-codex-window-type="electron"] [class*="viewer"] [style*="color: #24292e"],
[data-codex-window-type="electron"] [class*="viewer"] [style*="color: rgb(0, 0, 0)"],
[data-codex-window-type="electron"] [class*="viewer"] [style*="color: rgba(0, 0, 0"] {
  color: var(--vscode-editor-foreground) !important;
}

[data-codex-window-type="electron"] pre .hljs,
[data-codex-window-type="electron"] pre .hljs *,
[data-codex-window-type="electron"] code .hljs,
[data-codex-window-type="electron"] code .hljs *,
[data-codex-window-type="electron"] pre .token,
[data-codex-window-type="electron"] pre .token *,
[data-codex-window-type="electron"] code .token,
[data-codex-window-type="electron"] code .token * {
  color: color-mix(in oklab, var(--vscode-editor-foreground) 72%, currentColor 28%) !important;
}

[data-codex-window-type="electron"] pre span[style*="color:#000"],
[data-codex-window-type="electron"] pre span[style*="color: #000"],
[data-codex-window-type="electron"] pre span[style*="color:#111"],
[data-codex-window-type="electron"] pre span[style*="color: #111"],
[data-codex-window-type="electron"] pre span[style*="color:#24292e"],
[data-codex-window-type="electron"] pre span[style*="color: #24292e"],
[data-codex-window-type="electron"] pre span[style*="color: rgb(0, 0, 0)"],
[data-codex-window-type="electron"] pre span[style*="color: rgba(0, 0, 0"],
[data-codex-window-type="electron"] code span[style*="color:#000"],
[data-codex-window-type="electron"] code span[style*="color: #000"],
[data-codex-window-type="electron"] code span[style*="color:#111"],
[data-codex-window-type="electron"] code span[style*="color: #111"],
[data-codex-window-type="electron"] code span[style*="color:#24292e"],
[data-codex-window-type="electron"] code span[style*="color: #24292e"],
[data-codex-window-type="electron"] code span[style*="color: rgb(0, 0, 0)"],
[data-codex-window-type="electron"] code span[style*="color: rgba(0, 0, 0"] {
  color: var(--vscode-editor-foreground) !important;
}

::selection {
  background: $sel_bg !important;
  color: $sel_fg !important;
}

[data-codex-window-type="electron"] button,
[data-codex-window-type="electron"] [role="button"] {
  border-radius: 10px !important;
}
CSS

echo "Applied $THEME -> $CSS_TARGET"
echo "If injector is running in watch mode, Codex updates automatically."
